### ISSUE TITLE
4.5 target

### ISSUE THREAD

**Issue by davetheninja** [PolarbearDK/NUnit.DeepObjectCompare#1]
Could you possibly release another version that supports 4.5 as well as current 4.5.2?

Can't upgrade at my work for now and this project looks like what I'm after 

Thanks

**Comment by PolarbearDK** [comment]
Sorry, I was not watching this project for some reason. 
Looking at it now.

**Comment by PolarbearDK** [comment]
I have released a fix for it.

**Comment by davetheninja** [comment]
Most excellent sir. Thank you
