### ISSUE TITLE
Adopt a License

### ISSUE THREAD

**Issue by dsherret** [PolarbearDK/NUnit.DeepObjectCompare#2]
Hello, I went to try out this project, but it doesn't have a license file. Perhaps consider adopting a license so people can know if they can use this? Thanks!

**Comment by PolarbearDK** [comment]
Better now?

**Comment by filiptesar** [comment]
Hello, I have the same problem - I would like to use the library, but there is no license file or license information. Thank you!

**Comment by PolarbearDK** [comment]
Done?

**Comment by dsherret** [comment]
LGTM. Thanks @PolarbearDK!

**Comment by filiptesar** [comment]
Great! Thank you @PolarbearDK!
